### ISSUE TITLE
ServletResponseFactory class not found

### ISSUE THREAD

**Issue by driverpt** [micronaut-projects/micronaut-aws#2363]
### Expected Behavior

No errors to occur

### Actual Behaviour

Unable to load default response factory for definition [Optional[io.micronaut.core.io.service.DefaultServiceDefinition@40ebb56]]: Call to load() when class 'io.micronaut.servlet.http.ServletResponseFactory' is not present

See:
https://github.com/micronaut-projects/micronaut-servlet/issues/909
https://github.com/micronaut-projects/micronaut-servlet/pull/904

### Steps To Reproduce

Create a simple Exception handler returning an HttpResponse

### Environment Information

- OS: AWS Lambda J21 Runtime

### Version

4.8.2

**Comment by driverpt** [comment]
This appears to occur, because `ServletResponseFactory` was removed in `microaut-servlet` version 5.2.2

**Comment by driverpt** [comment]
Workaround, force Micronaut Servlet BOM to 5.2.1

i.e.:
```
implementation(enforcedPlatform("io.micronaut.servlet:micronaut-servlet-bom:5.2.1"))
```

**Comment by yawkat** [comment]
Can you give more information like a dependency tree? Or even a reproducer?

**Comment by driverpt** [comment]
Just create simple HTTP AWS Lambda Function using `implementation("io.micronaut.aws:micronaut-function-aws-api-proxy")`. 

It's even reproducible in Tests (using rest-assured for example)

Stacktrace Example:

```
16:53:18.100 [HTTP-Dispatcher] WARN  i.m.http.DefaultHttpFactories - Unable to load default response factory for definition [Optional[io.micronaut.core.io.service.DefaultServiceDefinition@4c470b01]]: Call to load() when class 'io.micronaut.servlet.http.ServletResponseFactory' is not present
java.util.ServiceConfigurationError: Call to load() when class 'io.micronaut.servlet.http.ServletResponseFactory' is not present
	at io.micronaut.core.io.service.DefaultServiceDefinition.lambda$load$1(DefaultServiceDefinition.java:78)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at io.micronaut.core.io.service.DefaultServiceDefinition.load(DefaultServiceDefinition.java:78)
	at io.micronaut.http.DefaultHttpFactories.resolveDefaultResponseFactory(DefaultHttpFactories.java:71)
	at io.micronaut.http.HttpResponseFactory.<clinit>(HttpResponseFactory.java:29)
	at io.micronaut.http.HttpResponse.created(HttpResponse.java:280)
	at com.somecompany.somemodule.controller.SomeController.submit(SomeController.java:666)
```

And I'm pretty sure it's related to this https://github.com/micronaut-projects/micronaut-aws/blob/4.11.x/function-aws-api-proxy/src/main/resources/META-INF/services/io.micronaut.http.HttpResponseFactory

**Comment by graemerocher** [comment]
It is likely be use of the presence of this file https://github.com/micronaut-projects/micronaut-aws/blob/9362db9481f862b4ff78b4f6afe0526ddd980c0b/function-aws-api-proxy/src/main/resources/META-INF/services/io.micronaut.http.HttpResponseFactory

**Comment by graemerocher** [comment]
@dstepanov @sdelamo @yawkat we have other references to this deleted class that need to be corrected https://github.com/search?q=org%3Amicronaut-projects%20io.micronaut.servlet.http.ServletResponseFactory&type=code

**Comment by sdelamo** [comment]
resolved via https://github.com/micronaut-projects/micronaut-aws/pull/2371

**Comment by driverpt** [comment]
When is this due to be released?

**Comment by henryju** [comment]
FYI, waiting for a new version of the platform catalog, the workaround I used is to add:

```
[versions]

micronaut-aws = "4.11.0" # override version of micronaut-aws https://github.com/micronaut-projects/micronaut-platform/blob/c3ab4f5e22c77df7cd07751debd826acd59f4a2b/gradle/libs.versions.toml#L15 to solve https://github.com/micronaut-projects/micronaut-aws/issues/2363
```
in the file `gradle/mn-override.versions.toml`

**Comment by albrechtflo-hg** [comment]
This still occurs in same setup, but with GCP Functions.

As a personal side note: Is it normal for you to remove a class referenced in multiple Service Locator files in a MINOR release (5.2.2) of a library?
